spring:
 jpa:
   show-sql: true
   hibernate:
     ddl-auto: update
 
  
 
 boot:
   admin:
     client:
       url:
       - http://172.23.239.225:9000
 application:
   name: PatientAuth



 datasource:
   url: jdbc:mysql://localhost:3306/PatientAuthDBMySQL
   username: root
   password: root123