server:
  port: 9001
  
spring:
  application:
    name: ConfigService
  boot:
    admin:
      client:
        url:
        - http://172.23.239.225:9000
  cloud:
    config:
      server:
        git:
          uri: https://github.com/sonu3706/spring-cloud-config-demo